# Generated by Django 5.2 on 2025-04-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_message"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
